### ISSUE TITLE
[ISSUE] Cannot display graphs in FR language

### ISSUE THREAD

**Issue by werdeil** [AF-1/lms-visualstatistics#14]
## Checklist

❗️ **Please take a quick look at [**this checklist**](https://github.com/AF-1/sobras/wiki/Checklist-to-eliminate-common-causes-of-LMS-(plugin)-problems) to eliminate common causes of LMS (plugin) problems. Thank you.**
<br><br><br>

---

## DESCRIBE THE BUG
In FR language I cannot manage to open any graph statistics, only the text one is working.
We had this issue few years ago, I can't remember how you fixed it.

I cleared the cache of the browser and all but no change. Happens on both Safari and Chrome. When I switch my server to EN, it manage to get the graphs. 

<br><br>
## TO REPRODUCE
1. Put your server in FR (I guess any language other than EN will be the same
1. Go to statistics plugin
2. Click on one graph statistics
3. Nothing happens.

<br><br>
## EXPECTED BEHAVIOR
Open the corresponding graph.

<br><br>
## LOG EXCERPT
I put my plugin in debug mode but I can't see any event in the logger when clicking on the menu.

<br><br>
## VERSION INFO
* LMS version: 9.0.0 - 1720934471
* OS (version): Debian - FR - utf8
* Plugin version: 1.7.4
* Web skin/controller:  LMS default
* Browser (version): Safari 17.5, Chrome 126.

If the problem occurs with a specific web skin/controller (e.g. Material), please check whether it also occurs when using other web skins/controllers (e.g. LMS default skin).

**Comment by AF-1** [comment]
This is probably due to your translation update I merged a while ago. I didn't see it then but it contained single quotes which break some things. I'l replace them and push an update.

**Comment by werdeil** [comment]
Thanks a lot and sorry for missing the quotes in my translations
